# Railway configuration for full-stack deployment
[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
FLASK_ENV = "production"
PORT = "5000"
